### ISSUE TITLE
fisherz test occasionally (but rarely) errors out

### ISSUE THREAD

**Issue by rflperry** [cmu-phil/causal-learn#29]
I am unsure why, but occasionally the fisherz test experiences the following error. I have not had this problem with the KCI test on the same data. I do not know if this is a bug or if it is a problem with the data. If a problem with the data, it would be more useful to be informed why.

>   File "/miniconda3/envs/causal/lib/python3.8/site-packages/causallearn/utils/cit.py", line 172, in fisherz
    r = -inv[0, 1] / sqrt(inv[0, 0] * inv[1, 1])
ValueError: math domain error

**Comment by kunwuz** [comment]
Thanks for letting us know. We will look into this. Meanwhile, if possible, could you please share a minimal code and sample dataset that could reproduce that issue?

**Comment by delacylab** [comment]
I get this error too, I stuck in some debug lines in the fisherz function and here are the variable values right before the crash:
var
[80, 8, 81, 82]

sub_corr_matrix
[[ 1.          0.05900512 -0.53968299 -0.77947494]
 [ 0.05900512  1.         -0.04393224 -0.0369982 ]
 [-0.53968299 -0.04393224  1.         -0.10670507]
 [-0.77947494 -0.0369982  -0.10670507  1.        ]]

sub_corr_matrix determinant -1.356916280487041e-15

inverse of sub_corr_matrix
[[-7.25887259e+14 -2.94842405e-01 -4.57331063e+14 -6.14610472e+14]
 [-3.00253318e-01  1.00370143e+00 -1.40868234e-01 -2.12238508e-01]
 [-4.57331063e+14 -1.37148843e-01 -2.88132487e+14 -3.87223301e+14]
 [-6.14610472e+14 -2.07321594e-01 -3.87223301e+14 -5.20392152e+14]]

The problem appears to be that elements in the inverse matrix are going to negative infinity. Why that is, I have no idea.

**Comment by jdramsey** [comment]
Sorry to intrude, but is it possible the matrix is not singular so when you invert it you don't get a proper inverse? Have you tried multiplying the inverse by the matrix to see if you get I?

**Comment by delacylab** [comment]
I multiplied the matrix and inverse matrix together like you suggested and did not get I or anything close. I checked the determinant of the matrix and it is basically 0. I researched this problem and numpy many times does not catch "basically 0" due to floating point math oddities so something is never 0 but will instead be e.g. 2.8e-14. They added an isclose function but I don't know enough about the math involved in causal-learn to guess what a good epsilon value would be to separate matrixes with legitimately very small determinants from matrixes whose determinant really is 0.

**Comment by tofuwen** [comment]
Hi @delacylab,

Thanks for researching, and finding the root cause.

Do you mind adding an assertion in our codebase to ensure the matrix is not singular before calling inverse?

In this way, we can throw a better error message to users so they know it's data issue, instead of the current confusing error message.

Of course, if you don't have time, please let us know! And we will find someone to implement this.

**Comment by kunwuz** [comment]
Hi, we have updated our code (https://github.com/cmu-phil/causal-learn/pull/58). We believe it's related to the original data, which might not satisfy the assumption of the singularity of its covariance matrix, so we throw an exception in that case. Please let us know if you think there are other reasons. Many thanks!
