### ISSUE TITLE
memory consumption

### ISSUE THREAD

**Issue by lockmatrix** [cmu-phil/causal-learn#67]
On my dataset (~3.6w, ~40 feats), I found it may use over 40GB memory, ( and I have not get it end successfully)
Maybe it needs to use some db to reduce max memory usage?

**Comment by kunwuz** [comment]
Could you please let me know which algorithm (if possible, also the hyper-parameters) you are using?

**Comment by lockmatrix** [comment]
I first use `causallearn.search.ConstraintBased.PC` and `Default: ‘fisherz’.` , memory keeps growing.

Now I am running `chisq`, and find memory consumption fluctuates wildly, about 5-55GB

**Comment by kunwuz** [comment]
Thanks for the information. Also, could you please let us know the types of your features? And if some of them are discrete, could you please let me know the cardinalities of them? I'm asking these because chisq is designed for discrete data and cardinalities matter a lot when it comes to RAM.

Besides, CC @MarkDana here, who is the expert on RAM-related questions of these two tests you mentioned :)

**Comment by lockmatrix** [comment]
feats are mixed, some are discrete, some are real-value

**Comment by MarkDana** [comment]
Hi there. Thanks for identifying this! I will take a look in days :)

**Comment by MarkDana** [comment]
May I ask which causal-learn version are you using?

Seems that nan is contained in the data?

**Comment by lockmatrix** [comment]
> May I ask which causal-learn version are you using?

causal-learn 0.1.2.8

> Seems that nan is contained in the data?

I tried replace nan with 0 with fisherz, fisherz still has memory issue

**Comment by MarkDana** [comment]
Hi there! The data 1) contains nan values and 2) two features are constants. If we directly remove these invalid data points:

```python
# data initially in shape (36188, 42)
data = data[~np.isnan(data).any(axis=1)]  # remove rows with nan values
data = data[:, np.var(data, axis=0) > 0]  # remove columns [20, 27] with constant values
# now data is in shape (27952, 40)

pc(data, 0.05, fisherz)
```

Then pc will end in `14.9s` with a maximum memory of `275MiB`. This is reasonable. 

For nan values in data, the newest version of causal-learn should throw an error at the beginning I guess? Of course, directly deleting nan rows or replacing nan elements is not the best solution. You may want to have a look at `MVPC`?

For nan values in the correlation matrix (due to constant columns and thus zero variance at the denominator) -- big thanks for identifying this! We will add a precheck to data and assign zero corr with any other for constant variables.

Hope this solves your issue. Or should there be any further comments, please kindly let us know :)

**Comment by lockmatrix** [comment]
Thanks, simple remove rows will remove too much, I will try remove cols

**Comment by MarkDana** [comment]
@lockmatrix @kunwuz I think this issue is ready to be closed. Thanks ;)

**Comment by lockmatrix** [comment]
It works, it seems the nan is the problem.
Maybe should add a warning for it in algo can not handle it ?
