### ISSUE TITLE
CD-NOD outputs directed cycles.

### ISSUE THREAD

**Issue by lmz123321** [cmu-phil/causal-learn#75]
Hi, Thanks for your great work.

When I am using CD-NOD in my private data, I realize the output PDAG contains a directed cycle.

I use KCI test, other settings (e.g. orientation rules) are set exactly as default values in the illustration example.

Any idea why this phonomene shows? How should I solve this bug?

**Comment by kunwuz** [comment]
Hi, thanks for the great question. From my perspective, it might not be a bug--sometimes the cycle happens when the data does not meet the faithfulness assumption. The same phenomenon occurs in PC and FCI, too. Could you please try it on simulated data, i.e., the one you are sure faithfulness does not violate, to see if there are any cycles?

**Comment by lmz123321** [comment]
Thanks for your answer. The simulation data is just fine. I guess it may be the assumption violation problem.
